spring.application.name=EmailDemoApp                                                                                                                           spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=vasavibalabhadra2@gmail.com
spring.mail.password=mdcx rzjn xyjn pufv

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true